#!/bin/bash
cd /home/ec2-user/ruby-sinatra
gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
curl -L get.rvm.io | bash -s stable
source /etc/profile.d/rvm.sh
rvm requirements
rvm install 2.3.0
gem install sinatra
gem install json
gem install bundler
yum install -y ruby-devel
gem install io-console
bundle install
bundle exec rackup -p 80 -o 0.0.0.0 -D
